In [1]:
# ! pip install gym
# !pip install matplotlib

In [1]:
# !pip install stable-baselines3[extra]
# !pip install pyglet==1.5.27
# !pip install --user --upgrade git+http://github.com/pyglet/pyglet@pyglet-1.5-maintenance
# ! conda install -n base -c conda-forge widgetsnbextension
# ! conda install -n pyenv -c conda-forge ipywidgets
# !pip install gym[all]

In [2]:
import os
import gym
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy

## Make envirnment

In [3]:
env_name = 'CartPole-v0'
env = gym.make(env_name)

In [4]:
env.reset()

array([-0.03654802, -0.00640843,  0.03211552,  0.04472201], dtype=float32)

In [5]:
# In this code we use random steps
# This code is to check the working
# Model predictions are not being used
episodes = 50
for epi in range(1,episodes+1):
    state = env.reset()
    done = False
    score = 0

    while not done:
        env.render()
        # This step is not a prediction
        # It is a random step
        action = env.action_space.sample()
        n_state, reward, done, info = env.step(action)
        score+=reward
    print('Episocde {}: Score {}'.format(epi,score))
env.close()

Episocde 1: Score 13.0
Episocde 2: Score 21.0
Episocde 3: Score 40.0
Episocde 4: Score 25.0
Episocde 5: Score 12.0
Episocde 6: Score 36.0
Episocde 7: Score 12.0
Episocde 8: Score 22.0
Episocde 9: Score 23.0
Episocde 10: Score 13.0
Episocde 11: Score 68.0
Episocde 12: Score 10.0
Episocde 13: Score 49.0
Episocde 14: Score 13.0
Episocde 15: Score 14.0
Episocde 16: Score 23.0
Episocde 17: Score 13.0
Episocde 18: Score 18.0
Episocde 19: Score 14.0
Episocde 20: Score 48.0
Episocde 21: Score 19.0
Episocde 22: Score 34.0
Episocde 23: Score 10.0
Episocde 24: Score 15.0
Episocde 25: Score 28.0
Episocde 26: Score 18.0
Episocde 27: Score 13.0
Episocde 28: Score 15.0
Episocde 29: Score 32.0
Episocde 30: Score 13.0
Episocde 31: Score 18.0
Episocde 32: Score 11.0
Episocde 33: Score 12.0
Episocde 34: Score 33.0
Episocde 35: Score 16.0
Episocde 36: Score 30.0
Episocde 37: Score 21.0
Episocde 38: Score 21.0
Episocde 39: Score 10.0
Episocde 40: Score 28.0
Episocde 41: Score 29.0
Episocde 42: Score 28.0
E

## Abou the envirnment

In [6]:
env.action_space

Discrete(2)

In [7]:
env.action_space.sample()

0

In [8]:
env.observation_space

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)

In [9]:
env.observation_space.sample()

array([ 1.1311160e+00, -1.6098379e+38, -4.0797880e-01,  2.3243923e+38],
      dtype=float32)

In [10]:
log_path = os.path.join('RLdata','Logs')
log_path

'RLdata/Logs'

### Training a PPO model

In [11]:
env = gym.make(env_name)
env = DummyVecEnv([lambda:env])
model = PPO('MlpPolicy',env,verbose=1,tensorboard_log=log_path)

Using cpu device


In [12]:
model.learn(total_timesteps=20000)

Logging to RLdata/Logs/PPO_2
-----------------------------
| time/              |      |
|    fps             | 3777 |
|    iterations      | 1    |
|    time_elapsed    | 0    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 2678        |
|    iterations           | 2           |
|    time_elapsed         | 1           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.008788876 |
|    clip_fraction        | 0.0842      |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.686      |
|    explained_variance   | 0.000796    |
|    learning_rate        | 0.0003      |
|    loss                 | 5.46        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0128     |
|    value_loss           | 51.6        |
-----------------------------------------
-----

### Save and reload a model

In [13]:
PPO_Path = os.path.join('RLdata','SavedModels','PPO_carpole')

In [14]:
model.save(PPO_Path)

In [15]:
del model

In [16]:
model = PPO.load(PPO_Path,env=env)

## Evaluation

In [17]:
evaluate_policy(model,env,n_eval_episodes=10,render=True)

/home/nextg3/miniconda3/envs/rl/lib/python3.10/site-packages/stable_baselines3/common/evaluation.py:65: UserWarning: Evaluation environment is not wrapped with a ``Monitor`` wrapper. This may result in reporting modified episode lengths and rewards, if other wrappers happen to modify these. Consider wrapping environment first with ``Monitor`` wrapper.
  warnings.warn(


(200.0, 0.0)

In [18]:
env.close()

## Using Model predictions

In [19]:
# In this code we use Predictions
# The predictions are made on observations
# Model predictions are being used
episodes = 50
for epi in range(1,episodes+1):
    obs = env.reset()
    done = False
    score = 0

    while not done:
        env.render()
        # This step is a prediction
        # we add the _ to unpack the value
        # we do not need the second (states) part
        action, _ = model.predict(obs)
        obs, reward, done, info = env.step(action)
        score+=reward
    print('Episocde {}: Score {}'.format(epi,score))
env.close()

Episocde 1: Score [200.]
Episocde 2: Score [200.]
Episocde 3: Score [200.]
Episocde 4: Score [200.]
Episocde 5: Score [200.]
Episocde 6: Score [200.]
Episocde 7: Score [200.]
Episocde 8: Score [200.]
Episocde 9: Score [200.]
Episocde 10: Score [200.]
Episocde 11: Score [200.]
Episocde 12: Score [200.]
Episocde 13: Score [200.]
Episocde 14: Score [200.]
Episocde 15: Score [200.]
Episocde 16: Score [200.]
Episocde 17: Score [200.]
Episocde 18: Score [200.]
Episocde 19: Score [200.]
Episocde 20: Score [200.]
Episocde 21: Score [200.]
Episocde 22: Score [200.]
Episocde 23: Score [200.]
Episocde 24: Score [200.]
Episocde 25: Score [200.]
Episocde 26: Score [200.]
Episocde 27: Score [200.]
Episocde 28: Score [200.]
Episocde 29: Score [200.]
Episocde 30: Score [200.]
Episocde 31: Score [200.]
Episocde 32: Score [200.]
Episocde 33: Score [200.]
Episocde 34: Score [200.]
Episocde 35: Score [200.]
Episocde 36: Score [200.]
Episocde 37: Score [200.]
Episocde 38: Score [200.]
Episocde 39: Score [2

## Use tensorboard

In [20]:
train_log_path = os.path.join(PPO_Path,'PPO_1')

In [31]:
# !tensorboard --logdir={train_log_path}

## Adding a callback to Model Training

This is important for training large models

In [22]:
# Import Callback helpers
from stable_baselines3.common.callbacks import EvalCallback, StopTrainingOnRewardThreshold

In [23]:
save_path = os.path.join('RLdata','SavedModels')

In [25]:
# Setup callbaks
stop_callback = StopTrainingOnRewardThreshold(reward_threshold=200,verbose=1)

eval_callback = EvalCallback(env,
                             callback_on_new_best=stop_callback,
                             eval_freq=10000,
                             best_model_save_path=save_path,
                             verbose=1)


In [ ]:
model = PPO('MlpPolicy',env,verbose=1,tensorboard_log=log_path)

In [27]:
# Apply Callback to train step
model.learn(total_timesteps=20000, callback=eval_callback)

Logging to RLdata/Logs/PPO_3
-----------------------------
| time/              |      |
|    fps             | 3840 |
|    iterations      | 1    |
|    time_elapsed    | 0    |
|    total_timesteps | 2048 |
-----------------------------
------------------------------------------
| time/                   |              |
|    fps                  | 2589         |
|    iterations           | 2            |
|    time_elapsed         | 1            |
|    total_timesteps      | 4096         |
| train/                  |              |
|    approx_kl            | 0.0061245575 |
|    clip_fraction        | 0.0391       |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.52        |
|    explained_variance   | 0.296        |
|    learning_rate        | 0.0003       |
|    loss                 | 0.601        |
|    n_updates            | 110          |
|    policy_gradient_loss | -0.00253     |
|    value_loss           | 6            |
------------------------------

## Change Policies

In [28]:
net_arch = [dict(pi=[128,128,128,128], vf = [128,128,128,128])]

In [29]:
model = PPO('MlpPolicy',env,verbose=1,tensorboard_log=log_path,policy_kwargs={'net_arch':net_arch})

Using cpu device


In [30]:
model.learn(total_timesteps=20000,callback=eval_callback)

Logging to RLdata/Logs/PPO_4
-----------------------------
| time/              |      |
|    fps             | 3012 |
|    iterations      | 1    |
|    time_elapsed    | 0    |
|    total_timesteps | 2048 |
-----------------------------
-----------------------------------------
| time/                   |             |
|    fps                  | 1898        |
|    iterations           | 2           |
|    time_elapsed         | 2           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.009627117 |
|    clip_fraction        | 0.139       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.683      |
|    explained_variance   | -0.00476    |
|    learning_rate        | 0.0003      |
|    loss                 | 3.32        |
|    n_updates            | 10          |
|    policy_gradient_loss | -0.0159     |
|    value_loss           | 18.6        |
-----------------------------------------
-----

## Alternate Algo - DWN

In [31]:
from stable_baselines3 import DQN

In [32]:
model = DQN('MlpPolicy',env,verbose=1,tensorboard_log=log_path)

Using cpu device


In [34]:
model.learn(total_timesteps=20000)

Logging to RLdata/Logs/DQN_1
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.953    |
| time/               |          |
|    episodes         | 4        |
|    fps              | 9825     |
|    time_elapsed     | 0        |
|    total_timesteps  | 99       |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.924    |
| time/               |          |
|    episodes         | 8        |
|    fps              | 10839    |
|    time_elapsed     | 0        |
|    total_timesteps  | 160      |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.888    |
| time/               |          |
|    episodes         | 12       |
|    fps              | 11926    |
|    time_elapsed     | 0        |
|    total_timesteps  | 236      |
----------------------------------
--------------------------

----------------------------------
| rollout/            |          |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 108      |
|    fps              | 14565    |
|    time_elapsed     | 0        |
|    total_timesteps  | 2362     |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 112      |
|    fps              | 14657    |
|    time_elapsed     | 0        |
|    total_timesteps  | 2475     |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 116      |
|    fps              | 14788    |
|    time_elapsed     | 0        |
|    total_timesteps  | 2597     |
----------------------------------
----------------------------------
| rollout/          

----------------------------------
| rollout/            |          |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 216      |
|    fps              | 15526    |
|    time_elapsed     | 0        |
|    total_timesteps  | 4899     |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 220      |
|    fps              | 15536    |
|    time_elapsed     | 0        |
|    total_timesteps  | 4992     |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 224      |
|    fps              | 15549    |
|    time_elapsed     | 0        |
|    total_timesteps  | 5084     |
----------------------------------
----------------------------------
| rollout/          

----------------------------------
| rollout/            |          |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 324      |
|    fps              | 15777    |
|    time_elapsed     | 0        |
|    total_timesteps  | 7412     |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 328      |
|    fps              | 15714    |
|    time_elapsed     | 0        |
|    total_timesteps  | 7496     |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 332      |
|    fps              | 15652    |
|    time_elapsed     | 0        |
|    total_timesteps  | 7597     |
----------------------------------
----------------------------------
| rollout/          

----------------------------------
| rollout/            |          |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 432      |
|    fps              | 15758    |
|    time_elapsed     | 0        |
|    total_timesteps  | 9878     |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 436      |
|    fps              | 15723    |
|    time_elapsed     | 0        |
|    total_timesteps  | 9969     |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 440      |
|    fps              | 15378    |
|    time_elapsed     | 0        |
|    total_timesteps  | 10084    |
----------------------------------
----------------------------------
| rollout/          

----------------------------------
| rollout/            |          |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 540      |
|    fps              | 15299    |
|    time_elapsed     | 0        |
|    total_timesteps  | 12196    |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 544      |
|    fps              | 15314    |
|    time_elapsed     | 0        |
|    total_timesteps  | 12307    |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 548      |
|    fps              | 15310    |
|    time_elapsed     | 0        |
|    total_timesteps  | 12401    |
----------------------------------
----------------------------------
| rollout/          

----------------------------------
| rollout/            |          |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 648      |
|    fps              | 15034    |
|    time_elapsed     | 0        |
|    total_timesteps  | 14770    |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 652      |
|    fps              | 15032    |
|    time_elapsed     | 0        |
|    total_timesteps  | 14858    |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 656      |
|    fps              | 15025    |
|    time_elapsed     | 0        |
|    total_timesteps  | 14931    |
----------------------------------
----------------------------------
| rollout/          

----------------------------------
| rollout/            |          |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 756      |
|    fps              | 15161    |
|    time_elapsed     | 1        |
|    total_timesteps  | 16938    |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 760      |
|    fps              | 15174    |
|    time_elapsed     | 1        |
|    total_timesteps  | 17055    |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 764      |
|    fps              | 15178    |
|    time_elapsed     | 1        |
|    total_timesteps  | 17128    |
----------------------------------
----------------------------------
| rollout/          

----------------------------------
| rollout/            |          |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 864      |
|    fps              | 15281    |
|    time_elapsed     | 1        |
|    total_timesteps  | 19433    |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 868      |
|    fps              | 15296    |
|    time_elapsed     | 1        |
|    total_timesteps  | 19559    |
----------------------------------
----------------------------------
| rollout/            |          |
|    exploration_rate | 0.05     |
| time/               |          |
|    episodes         | 872      |
|    fps              | 15307    |
|    time_elapsed     | 1        |
|    total_timesteps  | 19679    |
----------------------------------
----------------------------------
| rollout/          

# Project 1

In [1]:
import gym
from stable_baselines3 import A2C
from stable_baselines3.common.vec_env import VecFrameStack
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.env_util import make_atari_env
import os

## Test Env

 http://www.atarimania.com/roms/Roms.rar

In [2]:
# !which python3

In [3]:
# !python3 -m atari_py.import_roms ./ROMS/ROMS

In [4]:
env_name = 'Breakout-v0'
env = gym.make(env_name)

A.L.E: Arcade Learning Environment (version 0.7.4+069f8bd)
[Powered by Stella]


In [5]:
env.reset

<bound method TimeLimit.reset of <TimeLimit<AtariEnv<Breakout-v0>>>>

In [6]:
env.action_space

Discrete(4)

In [7]:
env.observation_space

Box([[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]], [[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
 

In [10]:
# In this code we use random steps
# This code is to check the working
# Model predictions are not being used
episodes = 50
for epi in range(1,episodes+1):
    obs = env.reset()
    done = False
    score = 0

    while not done:
        env.render()
        # This step is not a prediction
        # It is a random step
        action = env.action_space.sample()
        obs, reward, done, info = env.step(action)
        score+=reward
    print('Episocde {}: Score {}'.format(epi,score))
env.close()

Episocde 1: Score 2.0
Episocde 2: Score 0.0
Episocde 3: Score 2.0
Episocde 4: Score 1.0
Episocde 5: Score 2.0
Episocde 6: Score 0.0
Episocde 7: Score 2.0
Episocde 8: Score 0.0
Episocde 9: Score 4.0
Episocde 10: Score 0.0
Episocde 11: Score 0.0
Episocde 12: Score 1.0
Episocde 13: Score 3.0
Episocde 14: Score 5.0
Episocde 15: Score 2.0
Episocde 16: Score 2.0
Episocde 17: Score 0.0
Episocde 18: Score 1.0
Episocde 19: Score 3.0
Episocde 20: Score 2.0
Episocde 21: Score 4.0
Episocde 22: Score 0.0
Episocde 23: Score 1.0
Episocde 24: Score 1.0
Episocde 25: Score 1.0
Episocde 26: Score 3.0
Episocde 27: Score 4.0
Episocde 28: Score 2.0
Episocde 29: Score 1.0
Episocde 30: Score 0.0
Episocde 31: Score 4.0
Episocde 32: Score 0.0
Episocde 33: Score 0.0
Episocde 34: Score 1.0
Episocde 35: Score 3.0
Episocde 36: Score 1.0
Episocde 37: Score 0.0
Episocde 38: Score 3.0
Episocde 39: Score 3.0
Episocde 40: Score 1.0
Episocde 41: Score 0.0
Episocde 42: Score 2.0
Episocde 43: Score 0.0
Episocde 44: Score 3

## Vectorize the env

In [17]:
env = make_atari_env('Breakout-v0',n_envs=4, seed=0)
env = VecFrameStack(env,n_stack=4)

In [18]:
env.reset()

array([[[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        ...,

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         ...,
         [0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]],


       [[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0

In [19]:
log_path = os.path.join('RLdata','Logs')
model = A2C('CnnPolicy',env,verbose=1,tensorboard_log=log_path)

Using cpu device
Wrapping the env in a VecTransposeImage.


In [21]:
model.learn(total_timesteps=10000)

Logging to RLdata/Logs/A2C_3
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 274      |
|    ep_rew_mean        | 1.41     |
| time/                 |          |
|    fps                | 343      |
|    iterations         | 100      |
|    time_elapsed       | 5        |
|    total_timesteps    | 2000     |
| train/                |          |
|    entropy_loss       | -1.35    |
|    explained_variance | 0.495    |
|    learning_rate      | 0.0007   |
|    n_updates          | 149      |
|    policy_loss        | -0.488   |
|    value_loss         | 0.159    |
------------------------------------
------------------------------------
| rollout/              |          |
|    ep_len_mean        | 281      |
|    ep_rew_mean        | 1.56     |
| time/                 |          |
|    fps                | 336      |
|    iterations         | 200      |
|    time_elapsed       | 11       |
|    total_timesteps    | 4000     |
| train/ 

## Save the model

In [24]:
a2c_path = os.path.join('RLdata','SavedModels','A2C_Breakout_Model')
model.save(a2c_path)

In [25]:
del model

In [26]:
model = A2C.load(a2c_path, env)

Wrapping the env in a VecTransposeImage.


## Eval and test

In [33]:
single_env = make_atari_env('Breakout-v0',n_envs=1,seed=0)
single_env = VecFrameStack(single_env,n_stack=4)

In [35]:
evaluate_policy(model,single_env,n_eval_episodes=10,render=True)

(3.6, 1.9078784028338915)

# Create your own Env

Description

In [40]:
# Gym Dependencies
import gym
from gym import Env
from gym.spaces import Discrete, Box, Dict, Tuple, MultiBinary, MultiDiscrete

# Import helpers
import numpy as np
import random
import os

# Imprt stable baseline dependencies
from stable_baselines3 import PPO
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.evaluation import evaluate_policy

## Build the env
 - build an agent to give the best Difficulty of work
 - Availability will vary according to my dataset
 - Ideally, given the difficulty the Consensus time should be between 10-12 sec (agent doesn't know)

In [54]:
class ShoverEnv(Env):
    def __init__(self):
        self.action_space = Discrete(3)
#         self.observation_space = Box(low=np.array([0]), high = np.array([100]))
        self.observation_space = Box(low=0,high=100,shape=(1,))
        self.state = 38 + random.randint(-3,-3)
        self.shower_length = 60
        
    def step(self,action):
        # Apply temp
        self.state += action-1
        
        # Decrease shower time
        self.shower_length-=1
        
        # Calculate_reward
        if self.state>=37 and self.state<=39:
            reward = 1
        else:
            reward = -1
            
        if self.shower_length<=0:
            done = True
        else:
            done = False
            
        info = {}
        
        return self.state, reward, done, info
            
        
    def render(self):
        pass
    def reset(self):
        self.state = np.array([38+random.randint(-3,3)]).astype(float)
        self.shower_length = 60
        return self.state
    

In [55]:
env = ShoverEnv()

In [56]:
env.observation_space.sample()

array([21.718002], dtype=float32)

In [57]:
env.action_space.sample()

0

## Test Env

In [61]:
# In this code we use random steps
# This code is to check the working
# Model predictions are not being used
episodes = 5
for epi in range(1,episodes+1):
    obs = env.reset()
    done = False
    score = 0

    while not done:
        env.render()
        # This step is not a prediction
        # It is a random step
        action = env.action_space.sample()
        obs, reward, done, info = env.step(action)
        score+=reward
    print('Episocde {}: Score {}'.format(epi,score))
env.close()

Episocde 1: Score -58
Episocde 2: Score -46
Episocde 3: Score 20
Episocde 4: Score 32
Episocde 5: Score -50


## Train Model

In [62]:
log_path = os.path.join('RLdata','Logs')
model = PPO('MlpPolicy',env,verbose=1,tensorboard_log=log_path)

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [69]:
model.learn(total_timesteps=100000)

Logging to RLdata/Logs/PPO_7
---------------------------------
| rollout/           |          |
|    ep_len_mean     | 60       |
|    ep_rew_mean     | 18.2     |
| time/              |          |
|    fps             | 3472     |
|    iterations      | 1        |
|    time_elapsed    | 0        |
|    total_timesteps | 2048     |
---------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 60          |
|    ep_rew_mean          | 19.3        |
| time/                   |             |
|    fps                  | 2305        |
|    iterations           | 2           |
|    time_elapsed         | 1           |
|    total_timesteps      | 4096        |
| train/                  |             |
|    approx_kl            | 0.007374618 |
|    clip_fraction        | 0.14        |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.805      |
|    explained_variance   | -0.0149     |
|

------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 60           |
|    ep_rew_mean          | 42.1         |
| time/                   |              |
|    fps                  | 1833         |
|    iterations           | 11           |
|    time_elapsed         | 12           |
|    total_timesteps      | 22528        |
| train/                  |              |
|    approx_kl            | 0.0065775104 |
|    clip_fraction        | 0.135        |
|    clip_range           | 0.2          |
|    entropy_loss         | -0.781       |
|    explained_variance   | 3.33e-05     |
|    learning_rate        | 0.0003       |
|    loss                 | 24.8         |
|    n_updates            | 380          |
|    policy_gradient_loss | 0.000304     |
|    value_loss           | 65.6         |
------------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_m

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 60          |
|    ep_rew_mean          | 48.4        |
| time/                   |             |
|    fps                  | 1747        |
|    iterations           | 21          |
|    time_elapsed         | 24          |
|    total_timesteps      | 43008       |
| train/                  |             |
|    approx_kl            | 0.015786814 |
|    clip_fraction        | 0.163       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.715      |
|    explained_variance   | 8.82e-06    |
|    learning_rate        | 0.0003      |
|    loss                 | 43.5        |
|    n_updates            | 480         |
|    policy_gradient_loss | 0.000968    |
|    value_loss           | 93.6        |
-----------------------------------------
------------------------------------------
| rollout/                |              |
|    ep_len_mean          | 60  

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 60          |
|    ep_rew_mean          | 52.1        |
| time/                   |             |
|    fps                  | 1728        |
|    iterations           | 31          |
|    time_elapsed         | 36          |
|    total_timesteps      | 63488       |
| train/                  |             |
|    approx_kl            | 0.018099371 |
|    clip_fraction        | 0.188       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.74       |
|    explained_variance   | 3.89e-05    |
|    learning_rate        | 0.0003      |
|    loss                 | 45.7        |
|    n_updates            | 580         |
|    policy_gradient_loss | 0.0139      |
|    value_loss           | 91.6        |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 60    

-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 60          |
|    ep_rew_mean          | 56          |
| time/                   |             |
|    fps                  | 1725        |
|    iterations           | 41          |
|    time_elapsed         | 48          |
|    total_timesteps      | 83968       |
| train/                  |             |
|    approx_kl            | 0.010773823 |
|    clip_fraction        | 0.154       |
|    clip_range           | 0.2         |
|    entropy_loss         | -0.717      |
|    explained_variance   | 3.93e-06    |
|    learning_rate        | 0.0003      |
|    loss                 | 43.2        |
|    n_updates            | 680         |
|    policy_gradient_loss | 0.00903     |
|    value_loss           | 100         |
-----------------------------------------
-----------------------------------------
| rollout/                |             |
|    ep_len_mean          | 60    

## Save Model

In [70]:
shower_path = os.path.join('RLdata','SavedModels','ShowerModel')
model.save(shower_path)

## Eval

In [71]:
evaluate_policy(model,env,n_eval_episodes=10)

(59.4, 0.9165151389911679)